### ISSUE TITLE
Remove NuGet references to Revit dlls

### ISSUE THREAD

**Issue by adecler** [BHoM/Revit_Toolkit#350] opened 2019-07-11 04:17 UTC
#### Description:
Direct links to locally installed dlls need to be replaced by references through NuGet packages.
This is required so we can set up continuous integration on AppVeyor (where Revit is obviously not installed)

**Comment by FraserGreenroyd** [comment] 2019-07-18 16:11
To confirm, I am looking into this, it isn't being ignored, it's just in a host of open issues to resolve this week :smile:

**Comment by FraserGreenroyd** [comment] 2019-07-22 08:40
I have managed to find the appropriate API and API_UI Nuget packages, however, am struggling to find the appropriate API_IFC replacement - @ZiolkowskiJakub can you advise?

**Comment by FraserGreenroyd** [comment] 2019-07-22 15:27
I ended up using adding IFC to a repository libs folder similar to how we did for TAS. This will need reviewing thoroughly to ensure it works and is acceptable.

**Comment by ZiolkowskiJakub** [comment] 2019-07-24 09:43
Hi @FraserGreenroyd, @rwemay 

I reopen this issue due to fact Dynamo_Toolkit is not able to load dlls in SnadBox mode after the changes. It works fine when run directly from Revit.

This has been reported by @michaldengusiak  here:
https://github.com/BHoM/Dynamo_Toolkit/issues/159

**Comment by ZiolkowskiJakub** [comment] 2019-07-24 09:52
It seems the problem is related with local copy of Revit dlls I reported here:
https://github.com/BHoM/Revit_Toolkit/pull/353#issuecomment-514108925

**Comment by FraserGreenroyd** [comment] 2019-07-24 10:04
This issue has been resolved and a PR already merged so I'm re-closing it. If there is an issue with existing functionality it should be raised as a new issue. The ongoing Nuget discussion will get a new issue when it is ready to be resolved. However, I suspect this is caused by some other configuration issue. I'll raise a new issue to investigate.

**Comment by ZiolkowskiJakub** [comment] 2019-09-09 09:46
Debug2019 and Release2019 solution configuration does not reference correct dlls. It seems these two use dlls for Revit API 2018.

As far as I remember we had discussion with @FraserGreenroyd , @al-fisher, @rwemay current setup is temporary only however nothing happened so far to fix it.

**Comment by ZiolkowskiJakub** [comment] 2019-10-14 14:08
Current setup does not allow for changing version of referenced dlls.

The solution I found:
1. Migrate from packages.config to PackageReference ([link](https://docs.microsoft.com/en-us/nuget/consume-packages/migrate-packages-config-to-package-reference))
2. Add following lines to projects (*.csproj) which reference Revit API dlls (we would use following package: [link](https://www.nuget.org/packages/Autodesk.Revit.SDK/2020.0.0?_src=template)):
```
  <ItemGroup>
    <PackageReference Include="Autodesk.Revit.SDK" Condition="'$(Configuration)' == 'Debug2019'">
      <Version>2019.2.0</Version>
    </PackageReference>
    <PackageReference Include="Autodesk.Revit.SDK" Condition="'$(Configuration)' == 'Debug2018'">
      <Version>2018.0.0</Version>
    </PackageReference>
  </ItemGroup>
```
Disadvantages and known issues:
1. This solution requires Visual Studio 2017 or higher
2. There is issue with initialisation of NuGet package when Solution Configuration changed. The workaround requires to restart Visual Studio to load initialise correct version of NuGet package

More information:
* [Migrate from packages.config to PackageReference](https://docs.microsoft.com/en-us/nuget/consume-packages/migrate-packages-config-to-package-reference)
* [Autodesk.Revit.SDK](https://www.nuget.org/packages/Autodesk.Revit.SDK/2020.0.0?_src=template)
* [Package references (PackageReference) in project files](https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files)
* [NuGet packages.config is so yesterday](https://www.waitingimpatiently.com/package-reference-nuget/)

@adecler, @FraserGreenroyd, @IsakNaslundBh, @al-fisher, @rwemay any other solution you have in mind? What do you think?

**Comment by IsakNaslundBh** [comment] 2019-10-14 15:46
Myself as I think quite a few other people are on VS2015, so not sure a solution only working for 2017 and higher will work that well.

Not an expert in Nugets though, would be good if anyone else could have a look at whats been suggested by @ZiolkowskiJakub and check if there's any other solution available that will work with earlier versions.

**Comment by FraserGreenroyd** [comment] 2019-10-14 16:00
Agree with @IsakNaslundBh going for a VS2017 only solution isn't viable. I have this on my to-do list to look at for this milestone, @ZiolkowskiJakub do you have a desire to get it closed out on the ASAP side of the milestone?

**Comment by ZiolkowskiJakub** [comment] 2019-10-14 16:04
Agree on VS2017 I am still on 2015 as @IsakNaslundBh but this is only solution I found so far...

I would like to close this one due to fact this is quite core issue... We should start to think about migration to Revit 2020 soon... and it can be quite important to solve this one before that.

I look forward for any hints in this matter.

**Comment by ZiolkowskiJakub** [comment] 2019-10-17 14:32
Hi @FraserGreenroyd,

Thank you for your help today. I will be removing NuGet packages for Revit dlls and moving the dlls to libs folder as you recommended.

**Closed** 2019-10-18 08:25 UTC
Labels: severity:critical, type:external-api-changes
