### ISSUE TITLE
Revit_Toolkit: RevitAdapter GH node loses contact if it recomputes while Revit is open

### ISSUE THREAD

**Issue by JosefTaylor** [BHoM/Revit_Toolkit#71] opened 2018-07-23 18:22 UTC
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by pawelbaran** [comment] 2019-11-08 20:38
Closing this one as possibly resolved or a duplicate of #257

**Closed by pawelbaran** 2019-11-08 20:38 UTC
Labels: severity:medium, type:bug
