### ISSUE TITLE
Revit_Toolkit: Family Instance on MEP Curve Add Error Message

### ISSUE THREAD

**Issue by kayleighhoude** [BHoM/Revit_Toolkit#1162] opened 2022-01-20 19:08 UTC
#### Description:
Per recent issues explored with @pawelbaran and @michal-pekacki, let's add an error message regarding a union not being added to routing preferences prohibiting the placement of instance based objects onto MEP curves

![image](https://user-images.githubusercontent.com/34316256/150405583-f4f198a9-05cb-4297-bbb5-7f1dc03b4fda.png)

**Comment by michal-pekacki** [comment] 2023-01-05 09:30
I can't rearrange this issue and fire damper placement works correctly for "None" union preferences - do you have the same @kayleighhoude?

**Comment by vietle-bh** [comment] 2024-01-04 17:14
Closing this issue as we couldn't reproduce the error. Please reopen if necessary.

**Closed by vietle-bh** 2024-01-04 17:14 UTC
Labels: type:feature
