### ISSUE TITLE
Revit_Toolkit: Revit Settings Family Library Directory

### ISSUE THREAD

**Issue by kayleighhoude** [BHoM/Revit_Toolkit#260] opened 2019-03-07 19:40 UTC
Specified family library folder in the Revit settings, however the families didn't load and script wasn't functional until family was manually loaded in Revit.

Link to Sample Script for Creating Schematic Spaces:
https://github.com/BHoM/samples/commit/bf6e39bf5beea97b8dbfcb3fc6f382c4b808612d#diff-e1f3e1e7d11c4164e0f6a28cf6af54fc

**Comment by ZiolkowskiJakub** [comment] 2019-03-08 12:46
Hi @kayleighhoude,

Have you seen this #228

**Comment by pawelbaran** [comment] 2019-11-08 20:34
Closing this one as a duplicate of #228

**Closed by pawelbaran** 2019-11-08 20:34 UTC
Labels: severity:medium, type:bug
