### ISSUE TITLE
Revit_Toolkit: Walls not having correct elevation

### ISSUE THREAD

**Issue by jdarcyBHE** [BHoM/Revit_Toolkit#274] opened 2019-04-12 08:26 UTC
Pushing walls to Revit, there aren't assigned to the correct Level, and seem to be constrained to the lower two levels.

![image](https://user-images.githubusercontent.com/34092831/56022990-cb164f00-5d04-11e9-9706-4bc8b275c8bd.png)

There should be three levels of walls.

Work around possible by tagging walls with Level reference and manually adjusting in Revit.

**Comment by ZiolkowskiJakub** [comment] 2019-05-28 11:56
Hi @jdarcyBHE,

Can you please provide example for this issue. What kind of BHoM Object you use to create wall?

@pawelbaran: the issue is probably connected with Structural Objects. From this short description I can guess that the Unconnected Height parameter is not setup to correct value.

**Comment by pawelbaran** [comment] 2019-05-28 12:15
Yep, sounds like an issue on the Structures side. I will try to fix it once the current PRs get merged.

**Comment by rwemay** [comment] 2019-06-11 06:53
This still isn't working for me. It should be a very quick fix(?) Possible to expedite? Let me know if you need a test script - but I think good to set one up as part of the macro tests.

**Comment by ZiolkowskiJakub** [comment] 2019-06-11 07:04
HI @rwemay,

@IsakNaslundBh  is currently doing a lot of changes to pull and push IFramingElements. Whenever his stuff will be merged I will have a look at this issue. Otherwise we could have some conflicts with his changes.

**Comment by pawelbaran** [comment] 2019-09-09 13:52
@ZiolkowskiJakub @jdarcyBHE @rwemay could one of you replicate the issue from memory? I am plowing through the structural/physical push/pull issues, happy to chase that one too.

**Comment by pawelbaran** [comment] 2019-09-26 15:20
Considered closed with #376 - please reopen if occurs again.

**Closed by pawelbaran** 2019-09-26 15:20 UTC
Labels: discipline: Physical, severity:medium
