### ISSUE TITLE
Revit_Toolkit: Keep Building Element normal when pull push

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/Revit_Toolkit#219] opened 2019-01-23 16:52 UTC
we need to keep normal orientation - point order
![image](https://user-images.githubusercontent.com/26113670/51622702-0cca0180-1f2f-11e9-8fd4-ea00fdb5aa31.png)

after pull and push

![image](https://user-images.githubusercontent.com/26113670/51622690-03409980-1f2f-11e9-8f6c-b3a3a0fef6fd.png)

**Comment by michaldengusiak** [comment] 2019-09-18 09:50
to be fixed with #371

**Comment by pawelbaran** [comment] 2019-11-08 20:24
Closing that as a duplicate of #371

**Closed by pawelbaran** 2019-11-08 20:24 UTC
Labels: discipline: BEnv, severity:medium, type:bug
