### ISSUE TITLE
Include Internal Loops When Pulling Spaces From Revit

### ISSUE THREAD

**Issue by enarhi** [BHoM/Revit_Toolkit#1251] opened 2022-09-12 15:14 UTC
#### Description:
Spaces are currently pulled with only their external loop as their perimeter. This causes issues when we have spaces with internal loops that have other spaces within this internal loop.

#### Steps to reproduce:
Pull a "donut" space with an internal loop, as below:
![image](https://user-images.githubusercontent.com/6752345/189692500-37f9e3d8-254f-4fb0-a0c4-28ca5e05f825.png)

The space is pulled with only the external perimeter:
![image](https://user-images.githubusercontent.com/6752345/189682859-3e512160-81df-4a97-a992-1d0d4fd3ddfe.png)

#### Expected behaviour:
It is expected that the space would include its internal loops, as this is critical to the definition of the space.

#### Test file(s):
Pull any space with internal loops from Revit.

**Comment by pawelbaran** [comment] 2023-01-04 17:15
@enarhi I have just bumped into this issue. From what I can see, the way in which space is defined in the oM does not allow for internal loops (!). I guess it is not a coincidence, taken how long it was like that. @rboulton-BH @jamesramsden-bh thoughts?

**Comment by FraserGreenroyd** [comment] 2023-01-04 17:19
I can confirm, doughnut spaces are not valid BHoM spaces for the workflows developed within Environments, so the pulled space shouldn't include it's internal loops, but should perhaps split them into smaller rooms.

**Comment by vietle-bh** [comment] 2024-01-04 16:48
Closing this because the same issue has been raised where more appropriate.

**Closed by vietle-bh** 2024-01-04 16:48 UTC
Labels: type:bug
