### ISSUE TITLE
Remove Adapters namespace in the Engine classes

### ISSUE THREAD

**Issue by ZiolkowskiJakub** [BHoM/Revit_Toolkit#385] opened 2019-10-01 08:10 UTC
#### Broken rules:

As mentioned in #364 by @alelom the 'Adapters' namespace shall not exists in the Engine classes.

#### Suggestions to restore compliance:

Remove `Adapters` namespace from Engine classes.

Also, in the Adapter project, make sure the namespace should be `Adapter` and not `Adapters`. 
`Adapters` with the "s" should not exist in BHoM.

**Comment by ZiolkowskiJakub** [comment] 2019-10-01 08:22
@al-fisher, @IsakNaslundBh, @alelom if we remove 'Adapters' from namespace it will cause backward compatibility issues... Do you have any suggestions how to carry out this change? Using 'Deprecated' attribute will double amount of code and will be quite long process to go.

**Comment by al-fisher** [comment] 2019-10-01 08:40
Thanks @ZiolkowskiJakub - agreed the process to carry out these changes to effectively deprecate does need consideration and some planning before we launch in. 👍 
Looping in @adecler as some technical and process improvements to backwards compatibility and depreciation are being planned as shown yesterday.
@adecler - following our chats today, can you put a plan in place to communicate what is coming and when? - Thanks!

**Comment by ZiolkowskiJakub** [comment] 2019-10-01 08:45
@alelom just to confirm: do you want to remove it from Engine only? What about the rest?

Currently we have:
'BH.oM.Adapters.Revit'
'BH.Engine.Adapters.Revit'

**Comment by alelom** [comment] 2019-10-01 08:46
oM as well. Only things stored in the Adapter project should use the `Adapter` namespace. Note, using only one "s".

**Comment by ZiolkowskiJakub** [comment] 2019-10-01 08:51
Hi @alelom,

`BH.Adapter.Revit` is correct for Revit_Adapter.. 

`Adapters` for `BH.oM.Adapters.Revit` and `BH.Engine.Adapters.Revit` comes from old approach taken from the past

**Comment by pawelbaran** [comment] 2019-11-08 20:02
@alelom would you be fine with taking over this issue?

**Comment by pawelbaran** [comment] 2019-11-19 14:50
Guys, I can tackle this one (the sooner the better I guess). Happy to do the following renaming:
- `BH.oM.Adapters.Revit` to `BH.oM.Revit`
- `BH.Engine.Adapters.Revit` to `BH.Engine.Revit`

How to tackle that with regard to backwards compatibility? @adecler @al-fisher @rwemay

**Comment by IsakNaslundBh** [comment] 2019-11-19 15:09
Would hold off on especially the first of this until https://github.com/BuroHappoldEngineering/Operations_Toolkit/issues/100 has been confirmed.

Think we want to group software specific objects to avoid having them mix to much with the rest of the obejcts.

For the second one I guess we might want to add in 'External' as well, but has not really been discussed that much as of yet.

**Comment by alelom** [comment] 2019-11-19 15:15
`BH.Engine.External.Revit` was indeed the most successful option when we last discussed. I'd go for it, but I'd officially formalise it, what do you say @al-fisher ?

**Comment by pawelbaran** [comment] 2019-11-19 15:25
Not being involved in the discussion at all, I am happy to unassign myself from this one 🐒

**Comment by alelom** [comment] 2019-11-19 15:31
I'd say go for it.

> Guys, I can tackle this one (the sooner the better I guess). Happy to do the following renaming:
> 
> * `BH.oM.Adapters.Revit` to `BH.oM.Revit`
> * `BH.Engine.Adapters.Revit` to `BH.Engine.Revit`

For the second one, use:
`BH.Engine.External.Revit` 

if we then change mind on the `external`, it's just a find-replace. But at least in the meantime the namespace would be sorted correctly.

With regards to the backwards compatibility, that's something additional to be checked with @adecler

**Comment by al-fisher** [comment] 2019-11-19 16:14
Great thanks guys.
From https://github.com/BuroHappoldEngineering/Operations_Toolkit/issues/100 looks like all still in agreement.
Let's proceed with `External` @pawelbaran 👍

**Comment by al-fisher** [comment] 2019-11-19 16:22
> How to tackle that with regard to backwards compatibility? @adecler @al-fisher @rwemay

@adecler has specifically implemented the ability to deprecate where there is a change of namespace only. See PR here: https://github.com/BHoM/Versioning_Toolkit/pull/4
Be good for you to use this as a use-case and further testing of this approach @pawelbaran ! Should be good.
Also @adecler is there any further documentation on how to deprecate to link people too? Useful for more guys to help stress test some of the cases you have already ticked off - appreciate there are a few more cases to come for UI etc. Cheers

**Comment by adecler** [comment] 2019-11-20 01:58
See comment in https://github.com/BHoM/Revit_Toolkit/issues/450#issuecomment-555799107
Documentation will come next once the process of versioning has been refined a bit. FYI, in the long run, I intend to have code added to the versioning engine automatically for trivial cases through the Visual studio toolkit (leveraging VS refactoring tools) since the manual process is a bit dull and repetitive.

**Comment by alelom** [comment] 2020-03-12 14:18
I'm closing this as it has been replaced by https://github.com/BHoM/Revit_Toolkit/issues/517.

**Closed by alelom** 2020-03-12 14:18 UTC
Labels: severity:critical, type:compliance
