### ISSUE TITLE
Revit_Toolkit: Update use to non deprecated methods for IsVertical

### ISSUE THREAD

**Issue by kThorsager** [BHoM/Revit_Toolkit#495] opened 2020-01-07 17:48 UTC
#### Broken rules:

https://github.com/BHoM/Revit_Toolkit/blob/b05e1a1749bf0d4f5ab9a4627adb19d3ed748356/Engine_Revit_UI/Convert/Physical/ToBHoM/FramingElement.cs#L161
After https://github.com/BHoM/BHoM_Engine/pull/1402 is merged this and other references to `IsVertical` will need to be updated call from Geometry_Engine instead of the Structure_Engine.
The old version is still available but deprecated and will be removed later.

#### Suggestions to restore compliance:

`IsVertical` has been moved to the Geometry_Engine and will have to be referenced from there

**Comment by FraserGreenroyd** [comment] 2020-01-07 22:30
Assigning to 3.1 milestone as I think this would be good to do this milestone while the issue is fresh in everyone's mind @pawelbaran @kThorsager

**Comment by pawelbaran** [comment] 2020-01-08 09:01
I guess this is on me.

**Comment by FraserGreenroyd** [comment] 2020-01-08 09:01
> I guess this is on me.

You guess correctly :wink:

**Closed** 2020-01-22 16:03 UTC
Labels: type:compliance
